@baseUrl = http://localhost:7000

###
# Invalid URI
GET {{baseUrl}}/x

###
# /user => method: GET
POST {{baseUrl}}/v1/sign-up
Content-Type: application/json

{
  "email": "mhf@123",
  "password": "Mhf2021$"
}

###
# /user => method: GET
POST {{baseUrl}}/v1/login
Content-Type: application/json

{
  "email": "mhf@123",
  "password": "Mhf2021$"
}